[[headers]]
  for = "/OneSignalSDKWorker.js"
  [headers.values]
    Content-Type = "application/javascript"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/OneSignalSDK.sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/*OneSignalSDKWorker.js*"
  [headers.values]
    Content-Type = "application/javascript"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/*OneSignalSDK.sw.js*"
  [headers.values]
    Content-Type = "application/javascript"
    Service-Worker-Allowed = "/"

